dist: xenial
language: python
python:
- "3.5"
- "3.6"
services:
- postgresql
env:
- UMAP_SETTINGS=umap/tests/settings.py
before_install:
  - sudo apt-get install -y libgdal20
  - gdal-config --version
install:
- pip install .
- pip install -r requirements-dev.txt
script: make test
notifications:
  irc:
    channels:
    - "irc.freenode.net#umap"
    on_success: change
    on_failure: always
  email: false
branches:
  only:
  - master
