site_name: uMap
pages:
- Home: index.md
- Installation: install.md
- Contributing: contributing.md
- how-tos:
  - Ubuntu from scratch: ubuntu.md
  - Customize your uMap style: custom.md
  - Backups and sync: backup.md
- Changelog: changelog.md
theme: readthedocs
